---
abstract: 'Authentication plugin for Mojolicious'
author:
  - 'hayajo <hayajo@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-Web-Auth
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  LWP::Protocol::Net::Curl: 0.005
  Mojolicious: 3.02
  Net::Twitter::Lite: 0.10004
  WebService::Dropbox: 1.01
resources:
  repository: git://github.com/hayajo/Mojolicious-Plugin-Web-Auth.git
version: 0.01
